---
- name: enable routing and disable RPF
  lineinfile:
    dest: "{{sysctl_file}}"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: "^net.ipv4.ip_forward", line: "net.ipv4.ip_forward = 1"}
    - { regexp: "^net.ipv4.conf.default.rp_filter", line: "net.ipv4.conf.default.rp_filter = 0"}
  tags:
    - enable_routing

- name: create local bird folder
  file: path={{bird_folder_local}} state=directory recurse=yes
  delegate_to: localhost
  become: false
  when: save_local is defined and save_local == "enable"
  tags:
    - bird_setup
    - local

- name: render bird configuration locally
  template: src=bird.conf.j2 dest={{bird_conf_local}}
  delegate_to: localhost
  become: false
  when: save_local is defined and save_local == "enable"
  tags:
    - bird_setup
    - local

- name: render bird configuration
  template: src=bird.conf.j2 dest={{bird_conf}} mode=0644
  notify:
    - enable bird
    - restart bird
  tags:
    - bird_setup
