filters:
  leafs:
    import_ospf: |
        if (source = RTS_OSPF) && (net ~ [ 1.1.1.0/24+, 10.0.0.0/16+ ]) then {
                if ( ospf_metric1 < 1000) then {
                        accept;
                } else reject;
        }
        else reject;
    export_ospf: |
        if (source = RTS_DEVICE) && ( net ~ [ 1.1.1.0/24+ ] ) then {
                ospf_metric1 = 1000;
                accept;
        }
        else reject;
